# Generated by Django 3.1.4 on 2020-12-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accounttype',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
