# Generated by Django 3.1.4 on 2020-12-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_accounttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
